// Copyright (C) 2004 Arkadiy Vertleyb
// Use, modification and distribution is subject to the Boost Software
// License, Version 1.0. (http://www.boost.org/LICENSE_1_0.txt)

#ifndef BOOST_TYPEOF_REGISTER_FUNDAMENTAL_HPP_INCLUDED
#define BOOST_TYPEOF_REGISTER_FUNDAMENTAL_HPP_INCLUDED

#include <boost/typeof/typeof.hpp>

#include BOOST_TYPEOF_INCREMENT_REGISTRATION_GROUP()

BOOST_TYPEOF_REGISTER_TYPE(char);
BOOST_TYPEOF_REGISTER_TYPE(short);
BOOST_TYPEOF_REGISTER_TYPE(int);
BOOST_TYPEOF_REGISTER_TYPE(long);
BOOST_TYPEOF_REGISTER_TYPE(unsigned char);
BOOST_TYPEOF_REGISTER_TYPE(unsigned short);
BOOST_TYPEOF_REGISTER_TYPE(unsigned int);
BOOST_TYPEOF_REGISTER_TYPE(unsigned long);
BOOST_TYPEOF_REGISTER_TYPE(float);
BOOST_TYPEOF_REGISTER_TYPE(double);
BOOST_TYPEOF_REGISTER_TYPE(bool);
BOOST_TYPEOF_REGISTER_TYPE(void);

#endif//BOOST_TYPEOF_REGISTER_FUNDAMENTAL_HPP_INCLUDED
